CREATE TABLE IF NOT EXISTS usuarios(
    id INTEGER AUTO_INCREMENT  PRIMARY KEY,
    email VARCHAR(100)  NOT NULL UNIQUE,
    nome VARCHAR(50) NOT NULL,
    password VARCHAR(100) NOT NULL,
    role VARCHAR(30) NOT NULL,
    code VARCHAR(30),
    status BOOLEAN NOT NULL
);